### ISSUE TITLE
Could we prevent the lint generation?

### ISSUE THREAD

**Issue by massenz** [nebula-plugins/gradle-aggregate-javadocs-plugin#10]
Currently, running this plugin (which is awesome, thanks!) generates a lot of unnecessary warnings.
Would it be possible to have something akin to:

    subprojects {
      tasks.withType(Javadoc) {
        options.addStringOption('Xdoclint:none', '-quiet')
      }
    }

Or is there a way to prevent `doclint`?

**Comment by DanielThomas** [comment]
That doesn't work? We are using the `Javadoc` task type...

**Comment by massenz** [comment]
Yes, that was what confused me too :)
Unfortunately I can't share the code, but maybe I can make a simple repo to show.

But if you could give it a go and let me know if it's "user error" that'd be grand.
Thanks again!

**Comment by stewert72** [comment]
Sorry, but what must I do to disable doclint?

I have tried several things like 

```
subprojects {
  tasks.withType(Javadoc) {
    options.addStringOption('Xdoclint:none', '-quiet')
  }
}
```

or

```
  if (JavaVersion.current().isJava8Compatible()) {
    allprojects {
      tasks.withType(Javadoc) {
        options.addStringOption('Xdoclint:none', '-quiet')
      }
    }
  }
```

but I still get the javadoc error:

```
java.lang.AssertionError: annotation tree hasn't been attributed yet: @Deprecated()
        at com.sun.tools.javac.util.Assert.error(Assert.java:133)
        at com.sun.tools.javac.util.Assert.checkNonNull(Assert.java:118)
        at com.sun.tools.javac.comp.Check.validateTypeAnnotation(Check.java:2745)
...
```

If I generate javadoc of each sub project separately (by calling ```gradle javadoc``` for each project) all works fine.

**Comment by stewert72** [comment]
Ok. Seems this is not a problem of aggregateJavadocs. Find out that the option "Xdoclint:none" was set successfully (Found the set option in a temporary option file created by gradle). I have also tried to start javadoc from command line with "Xdoclint:none". Error is still there. May be javadoc have a problem/bug with my project settings / architecture / ...
